version: '3.1'
services:
  web:
    image: odoo:15
    depends_on:
      - db
    ports:
      - "80:8069"
    volumes:
      - ./custom-addons:/mnt/extra-addons
     
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

